### ISSUE TITLE
Create More Information on Cloud System Requirements

### ISSUE THREAD

**Issue by brookspatb1** [NIGMS/Fundamentals-of-Bioinformatics#1]
I'm a novice in the realm of Google Cloud Services. If you initially sign up for an account (at the time of writing this), they give you an introductory $300 credit for a duration of 90 days. Unfortunately, this requires that you link your credit card. I'm absolutely willing to do this (and have) but is there more information that could be included for the recommended "machine-type" to be spun up for this section? I believe this would help alleviate potential for incurring excessive costs for those of us using the material in a DIY fashion.

I understand that there is a linked repo to help explain some of this, but it seems that since the tutorial was created, that the Google web-interface has changed. I believe by adding recommended machine-type and other accessory info, this will provide clarity even in the face of future interface changes by Google.

**Comment by webermn** [comment]
Great suggestion! We'll look through the tutorials and plan to provide default suggestions for machine type.

In terms of linking one's credit card to use the free GCP credits (which can understandably be a challenge), NIH does have plans to subsidize researchers' use of these tutorials though something called the [NIH Cloud Lab](https://cloud.nih.gov/resources/cloudlab/). Today, Cloud Lab is available on GCP only to NIH researchers and staff—but within the next 1-2 months, it will be opened more broadly to the research community. So, please stay tuned for updates on this!

**Comment by kyleoconnell-NIH** [comment]
Closing issue as Cloud Lab has launched for university users through data science cores.
